# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SPOPSx-Ginsu
version:      0.57
version_from: SPOPSx/Ginsu.pm
installdirs:  site
requires:
    SPOPS:                         0.83

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
